name: Release

on:
  push:
    branches: [ NGXLIBRARIES-17_github-actions ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"

      - name: Configure Git User
        run: |
          git config --global user.email "bot@lerna-publish-action"
          git config --global user.name "@$GITHUB_ACTOR"
#          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/ildar-icoosoft/ngx-libraries
#        env:
#          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci

      - name: Authenticate with NPM Registry
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lerna diff
        run: lerna diff

#      - name: Lerna changed
#        run: lerna changed

#      - name: Lerna publish
#        run: npx lerna publish --contents dist --yes
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

