name: Release

on:
  push:
    branches: [ NGXLIBRARIES-17_github-actions ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci

      - name: Configure Git User
        run: |
          git config --global user.email "bot@lerna-publish-action"
          git config --global user.name "@$GITHUB_ACTOR"

      - name: Authenticate with NPM Registry
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lerna diff
        run: lerna diff

      - name: Lerna updated
        run: lerna updated

      - name: Lerna publish
        run: npx lerna publish --contents dist --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

